# Generated by Django 5.2.12 on 2026-03-26 05:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0002_remove_company_country_remove_company_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='created_at',
            new_name='created_timestamp',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='target',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 8 and 15 digits.', regex='^\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('email', 'company'), name='unique_email_per_company'),
        ),
    ]
